spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tinysakura/practice-config-repo
          #配置配置文件在本地的下载目录
          basedir: /Users/chenfeihao/Desktop/spring_cloud_practice/basedir
          username:
          password:
          search-paths: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

